### ISSUE TITLE
Allow an organization to restrict signup to SSO / SAML

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5512]
From a support request:
As an organization (with enterprise tier and SAML) I want to restrict the email domains that allowed to be invited to
1) control license consumption
2) restrict access to the content

Restricting just the invite to certain domains would not solve their problem since it would still allow people to accept the invite with non-company addresses which they could still use for signup after leaving the company.

## Acceptance criteria
* [ ] add a field to Organization to enforceSAML
* [ ] if a new user accepts an invite to Org, they are required to signup with SAML if enforceSAML is set
* [ ] if an existing user tries to accept the invite and he's not a SAML user of that Org, they must create a new account

**Comment by ackernaut** [comment]
Referencing this in this discussion: #5663

**Comment by jordanh** [comment]
Suggestion: this feature should be near where an admin could require/not require users to be verified emails, and, near where admins could add new org-wide integration provider configurations (e.g. oauth providers for Jira Server/other self-hosted integrations)

**Comment by mattkrick** [comment]
Alternate AC
- [ ] add an environment variable to set which login strategies are possible (email/pass, google, SAML)
- [ ] disable allowing signups based on the strategy (e.g. if env var doesn't allow email/pass, don't show the email/pass fields AND don't allow it in the server mutation)

**Comment by jordanh** [comment]
I prefer the alternate AC. See: #4666

**Comment by jordanh** [comment]
Came up in Sales meeting. 5 large, large accounts have all asked for this. 1 account won't pay until this work is completed. Will raise priority

**Comment by mattkrick** [comment]
@tianrunhe  says
> works for private cloud or on-premises, but what about those enterprise accounts that are mixed with other tiers in the public SAAS? Thanks!

Great question. Do we need to support this functionality for the cloud offering, or is this just for private managed instances? @jordanh

**Comment by drewhousman1010** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/55133101) 🔒  on the cloud offering says:

> In our Organization user list, I can see some using their personal @gmail.com (most others @[company domain])
> How can we enforce @[company domain] only to be provisioned in our org?

**Comment by mattkrick** [comment]
That's a great example. Personal org on a cloud offering if I'm looking at it correctly.
I'd say we absolutely should not have this be a feature for the freeloaders.

It's probably not a pro feature.
Maybe it's a feature for enterprise.
Definitely a feature for self-hosted enterprise.
If we can limit it to self-hosted enterprise, it gets a lot easier.

I'd say we do the alternate AC first because it's fast & solves the tension for self-hosted customers. this also solves the problem of spam accounts joining self-hosted instances.

If we need to do more, Georg's plan looks good (although we might want to just whitelist domains vs. force SAML. we'll have to get more user details)

**Comment by mattkrick** [comment]
From Retro:
- We go cheap env vars for now
- Georg's AC is good, we should not tie this to SCIM because not all folks who want this use SCIM
- This is ONLY for SAML. domain blocking for non-saml folks doesn't need to work because the primary concern is data exfiltration & de-provisioning users in SAML is the only way to guarantee that

**Comment by elielytz** [comment]
Is there any testing environment or requirements I should meet from my side (like to create/use enterprise email) that could allow me to test this feature?

**Comment by Dschoordsch** [comment]
@elielytz there are testing steps outlined in the linked pull request #5877.

**Comment by elielytz** [comment]
This issue was reproduced for testing.
Thanks, @Dschoordsch for the testing heads up.

## Testing results
### Sign-Up with SSO
Popup shows briefly but no error message appears, When trying to register SSO email which is not configured.

## Other Findings
User registration using email does not validate the availability/existence of email.

### How to reproduce

- Go to the sign-up page 
- Sign up using email
- write random email comes to your head ie (majimaji@elias.elisante)
- Enter password
- submit

This will create a new Parabol Account, without checking if that email exists or not.

**Comment by tianrunhe** [comment]
Hey @elielytz thanks for the testing!!  
  
> Popup shows briefly but no error message appears, When trying to register SSO email which is not configured.
Is this what Georg described [here](https://github.com/ParabolInc/parabol/pull/5877#pullrequestreview-856557236)? I'm pretty sure I fixed it. Could you provide a video? Thanks!

> User registration using email does not validate the availability/existence of email.
This is expected behavior. With password signup today, we don't validate email.

**Comment by elielytz** [comment]
Hi @tianrunhe, thanks for the prompt reply. It's the same as Georg described.
Here is the video

https://user-images.githubusercontent.com/45159239/150878356-ca7a4f77-4d8b-49b5-ab6e-38b76305e16e.mp4

Do you get something extra on your side, like a notification?

**Comment by elielytz** [comment]
For the case of email registration, thanks Bruce for letting me know that it's expected behavior for now. I will note it.

**Comment by tianrunhe** [comment]
@elielytz Thanks for the video! It is indeed an issue. I'll work on the fix. Thanks so much for finding this out!

**Comment by elielytz** [comment]
Thanks, @tianrunhe, you are welcome.

**Comment by tianrunhe** [comment]
> Hi @tianrunhe, thanks for the prompt reply. It's the same as Georg described. Here is the video
> 
> SSO\_testing02.mp4  
> Do you get something extra on your side, like a notification?

Fix has been pushed. Please re-test, thank you!

**Comment by elielytz** [comment]
Am working on it, I will update you shortly

**Comment by elielytz** [comment]
Am still getting the same issue. 
I have used Firefox & Brave browsers. In both normal mode and private/incognito mode.
To prevent cached files I cleared respective browser data and cache.

Here is the video..

https://user-images.githubusercontent.com/45159239/150885776-65b9dd30-7012-47aa-a8d2-32222d3e5e2c.mp4

**Comment by tianrunhe** [comment]
> Am still getting the same issue (a window pops and disappears). I have used Firefox & Brave browsers. In both normal mode and private/incognito mode. To prevent cached files I cleared respective browser data and cache.
> 
> Here is the video..
> 
> SSO\_testing03A.mp4

Did you do `git pull` to get my update and restart the app?

**Comment by elielytz** [comment]
Yes I did, but my **.env** file does not have testing keys for MAIL_SMPT_XXXX. I will wait for your update to be available in a staging environment so I can test it well.
